name: homenest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1
  flutter_animate: ^4.5.0
  flutter_staggered_grid_view: ^0.7.0
  google_maps_flutter: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Euclid-Circular
      fonts:
        - asset: assets/fonts/Euclid-Circular-Bold.ttf
          weight: 700
        - asset: assets/fonts/Euclid-Circular-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Euclid-Circular-Medium.ttf
          weight: 500
        - asset: assets/fonts/Euclid-Circular-Regular.ttf
          weight: 400
